repos:
  # -------------------------
  # Ruff (lint Python)
  # -------------------------
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff
        additional_dependencies: []
        args: ["--fix"]

  # -------------------------
  # Black (formatage)
  # -------------------------
  - repo: https://github.com/psf/black
    rev: 25.11.0
    hooks:
      - id: black
        language_version: python3.12

  # -------------------------
  # Pytest (tests)
  # -------------------------
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
  # -------------------------
  # MyPy (type checking, optionnel)
  # -------------------------
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs
          - djangorestframework-stubs
        args: ["--ignore-missing-imports"]
        name: mypy (type check)
        language_version: python3.12
        stages: [commit]