name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres # pragma: allowlist secret
          POSTGRES_PASSWORD: postgres # pragma: allowlist secret
          POSTGRES_DB: testdb # pragma: allowlist secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SQL_ENGINE: django.db.backends.postgresql_psycopg3
      SQL_DATABASE: testdb # pragma: allowlist secret
      SQL_USER: postgres # pragma: allowlist secret
      SQL_PASSWORD: postgres # pragma: allowlist secret
      SQL_HOST: 127.0.0.1
      SQL_PORT: 5432

      # Variables Django (fausses valeurs â†’ pas de secret)
      DJANGO_SUPERUSER_USERNAME: "ci_user" # pragma: allowlist secret
      DJANGO_SUPERUSER_EMAIL: "ci@example.com" # pragma: allowlist secret
      DJANGO_SUPERUSER_PASSWORD: "not-a-secret-ci-value"  # pragma: allowlist secret

      DEBUG: "True"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Sync dependencies with uv
        run: uv sync

      - name: Lint with Ruff
        run: uv run ruff check .

      - name: Format check with Black
        run: uv run black --check .

      - name: Type check with Mypy
        run: uv run mypy .

      - name: Run migrations
        run: uv run python manage.py migrate

      - name: Run tests
        run: uv run pytest
